---

- name: Install ies plugins du catalogue
  ansible.builtin.include_tasks: install-plugin-rule-engine-python.yml
  when: "'rule-engine-python' in irods_ies_plugins"
  tags: [irods]

- name: Configure iRODS server in catalog
  ansible.builtin.include_tasks: irods.yml

# init iRODS distribution for IES

- name: Initialize iRODS distribution for IES (catalog server)
  ansible.builtin.command:
    cmd:
      python3 /var/lib/irods/scripts/setup_irods.py
      --json_configuration_file=/etc/irods/setup_irods.json
    creates: "{{ irods_version_file }}"
