---

- name: Configure iRODS server in resources servers
  ansible.builtin.include_tasks: irods.yml

# init iRODS distribution for non-IES

# mimic setup_irods.py except for creating default resources with fixed path
- name: Initialize iRODS distribution for non-IES (resource only server)
  ansible.builtin.command:
    cmd: "cp {{ irods_version_file }}.dist {{ irods_version_file }}"
    creates: "{{ irods_version_file }}"
