---

galaxy_info:
  author: "Pierre Gay (@pigay)"
  description: maintainer
  company: MCIA

  role_name: irods

  license: CC-BY

  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - "7"
    - name: Ubuntu
      versions:
        - bionic
    - name: Debian
      versions:
        - bookworm

  galaxy_tags: []

dependencies: []
