---
# defaults file for ansible-role-irods

irods_zone_name: "demoZone"

irods_catalog_provider_hosts: ["localhost"]
irods_hosts: []

irods_default_resource_name: "demoResc"
irods_config_schema_version: "v4"
irods_version_file: /var/lib/irods/version.json

# set null for latest version
irods_version: null

irods_cs_ssl: false

# irods_admin_password: "MUST_BE_SET"
# irods_database_user_password_salt: "MUST_BE_SET"
# irods_negotiation_key: "MUST_BE_SET_WITH_A_32_BYTES_LONG_STRING"
# irods_db_password: "MUST_BE_SET"
# irods_server_control_plane_key: "MUST_BE_SET_WITH_A_32_BYTES_LONG_STRING"
# irods_zone_key: "MUST_BE_SET"

irods_db_host: "localhost"
irods_db_name: "ICAT"
# ODBC driver for postgres:
# CentOS: "PostgreSQL"
# Ubuntu: "PostgreSQL ANSI" or "PostgreSQL Unicode"
irods_db_odbc_driver: "{{ (ansible_distribution == 'Ubuntu')
                           | ternary('PostgreSQL ANSI', 'PostgreSQL')
                       }}"
irods_db_port: 5432
irods_db_username: "irods"

irods_server_control_plane_port: 1248
irods_xmsg_port: 1279

irods_server_port_range_start: 20000
irods_server_port_range_end: 20199

irods_zone_port: 1247
irods_zone_user: "rods"

irods_ssl_default_directory: "/etc/irods/certs"
irods_ssl_certificate_chain_file: "{{ irods_ssl_default_directory }}/server.crt"
irods_ssl_certificate_key_file: "{{ irods_ssl_default_directory }}/server.key"
irods_ssl_verify_server: "hostname"
irods_ssl_ca_certificate_file: "{{ irods_ssl_default_directory }}/ca.crt"
irods_ssl_dh_params_file: "{{ irods_ssl_default_directory }}/dhparams.pem"
