---
# handlers file for ansible-role-irods

- name: Stop irods
  ansible.builtin.systemd_service:
    name: irods
    state: stopped

- name: Start irods
  ansible.builtin.systemd_service:
    name: irods
    state: started

- name: Restart irods
  ansible.builtin.systemd_service:
    name: irods
    state: restarted
