---
# vars file for role irods

# yamllint disable-line rule:line-length
ansible_role_irods_is_catalog: |
  {{ inventory_hostname in irods_catalog_provider_hosts
     or 'localhost' in irods_catalog_provider_hosts }}

irods_package_extension: |
  {{ '' if irods_version is none else '=' + irods_version }}
irods_server_pkgname: "irods-server{{ irods_package_extension }}"

# To force an specific version# and avoid error "unmet dependencies"
# (Depends: irods-runtime (= 4.2.9) but 4.2.10 is to be installed)
# we have to specify dependencies version
irods_runtime_pkgname: "irods-runtime{{ irods_package_extension }}"

irods_icommands_pkgname: "irods-icommands{{ irods_package_extension }}"

irods_database_pkgname: |
  irods-database-plugin-postgres{{ irods_package_extension }}

irods_rule_engines_configurations:
  irods_rule_language:
    instance_name: irods_rule_engine_plugin-irods_rule_language-instance
    plugin_name: irods_rule_engine_plugin-irods_rule_language
    plugin_specific_configuration:
      re_data_variable_mapping_set:
        - core
      re_function_name_mapping_set:
        - core
      re_rulebase_set:
        - core
      regexes_for_supported_peps:
        - "ac[^ ]*"
        - "msi[^ ]*"
        - "[^ ]*pep_[^ ]*_(pre|post|except|finally)"

    shared_memory_instance: irods_rule_language_rule_engine

  cpp_default_policy:
    instance_name: irods_rule_engine_plugin-cpp_default_policy-instance
    plugin_name: irods_rule_engine_plugin-cpp_default_policy
    plugin_specific_configuration: {}

  python:
    instance_name: irods_rule_engine_plugin-python-instance,
    plugin_name: irods_rule_engine_plugin-python,
    plugin_specific_configuration: {}
